---

- name: Update System
  apt:
    update_cache: true
    upgrade: full

- name: Install basic programs
  apt:
    name:
      - git
      - curl
      - htop
      - ca-certificates
      - wireguard
      - iptables-persistant
    state: present
