services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1002
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    networks:
      main:
        ipv4_address: 172.16.90.4
    volumes:
      - ./config:/config
      - /nas/multimedia/cache:/cache
      - type: bind
        source: /nas/multimedia
        target: /media
    restart: 'always'

networks:
  main:
    name: main
    external: true
